In [1]:
%%HTML
<link rel="stylesheet" type="text/css" href="../custom.css">

# 応用計量分析２（第3回）







### 担当教員: 梶野 洸（かじの ひろし）


# 本日の内容
Python に慣れようの回

- Python とは？
- 環境構築
- 基本的な文法
- 数値計算

# Python とは？

- プログラミング言語の一つ
- 近年よく用いられる
    - 文法がわりと簡単
    - データ解析に関するライブラリが揃っている
    - 特にディープラーニングはほぼ Python

# Python のライブラリ (1/2)

- `numpy`, `scipy`
    - 科学計算ライブラリ
    - 行列計算、統計処理など
    - python ブームの火付け役？
- `pandas`
    - 時系列解析ライブラリ
    - R みたいなやつ

# Python のライブラリ (2/2)

- `keras`, `pytorch`, `chainer`
    - ディープラーニング用ライブラリ
    - ネットワークを組み替えるのが容易
    - ディープラーニングやるならこれらを使う
- `matplotlib`, `bokeh`, `plotly`
    - グラフを描くライブラリ

# 環境構築
どのようにコードを書いて実行するか

- `jupyter notebook` の利用を想定
    - コードの実行が簡単
    - 結果が見やすい
    - 起動の仕方は第一回の宿題参照

# 演習
Jupyter notebook を起動してください

# 基本的な文法

Hello, world!

In [2]:
print('Hello, world!')

Hello, world!


# 基本的な文法
四則演算

In [3]:
1 + 1 # 整数同士の足し算

2

In [4]:
1.0 + 1.0 # 実数同士の足し算

2.0

In [5]:
3-2 # 整数同士の引き算

1

In [6]:
3*2 # 整数同士の掛け算

6

In [7]:
5/3 # 割り算（Python3の場合、スラッシュで普通の割り算）

1.6666666666666667

In [8]:
5.0/3.0 # 実数同士の割り算

1.6666666666666667

In [8]:
5//3 # 整数同士の割り算で商を知りたい場合

1

In [9]:
5%3 # 整数同士の割り算で余りを知りたい場合

2

In [10]:
100+10/5 # 割り算は足し算より優先される

102.0

In [12]:
(100+10)/5 # カッコを使うと優先される演算を決められる

22.0

In [9]:
2 ** 10 # 累乗は **

1024

# 演習
1. 税込み1980円の

# 変数

In [12]:
x=1 # x に 1 を代入する
print(x)

1


In [13]:
x=1
x=2
print(x)

2


In [15]:
x=1
y=4
print(x*y)

4


In [18]:
x=0
x=x+1
print(x)

1


# 条件・if文

In [24]:
x = 1
print(x==1) # x が 1 と等しいとき True
print(x!=1) # x が 1 ではないとき True
print(x!=0) # x が 0 ではないとき True

True
False
True


In [9]:
x = 1
if x == 0: # if (条件): が if 文
    print('yay!') # かならず <tab> を打ってインデントを下げる！

In [11]:
x = 1
if x == 0: # if (条件): が if 文
print('yay!') # かならず <tab> を打ってインデントを下げる！

IndentationError: expected an indented block (<ipython-input-11-e07010cf2b42>, line 3)

In [27]:
x = 1
if x == 0:
    print('x=0')
else: # if 文の条件がFalseの場合に実行される
    print('x!=0')

x!=0


In [29]:
x = 1
if x == 0:
    print('x=0')
elif x == 1:
    print('x==1')
else:
    print('x!=0 and x!=1')

x==1


# for 文

In [33]:
for i in range(5): # range(5) だと 0,1,...,4
    print(i)        # for 文内はインデントを下げる

0
1
2
3
4


In [34]:
for i in range(5): # range(5) だと 0,1,...,4
print(i)

IndentationError: expected an indented block (<ipython-input-34-0e78f8284010>, line 2)

# 演習1
- $0$から$99$までの偶数を表示せよ
- $0$から$99$までの3の倍数を表示せよ
- Fizz Buzz 問題($99$まで)
    - 1,2,...から順に数を表示したい
    - 3の倍数のときは数字の代わりに 'Fizz' と表示
    - 5の倍数のときは数字の代わりに 'Buzz' と表示
    - 15の倍数のときは数字の代わりに 'FizzBuzz' と表示
    - 例: 1,2,Fizz,4,Buzz,...,13,14,FizzBuzz,16,...
    - ヒント: `range(1,100)` は$1$から$99$まで

1.$0$から$99$までの偶数を表示せよ

In [35]:
for i in range(100):
    if i % 2 == 0:
        print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


1. $0$から$99$までの3の倍数を表示せよ

In [36]:
for i in range(100):
    if i % 3 == 0:
        print(i)

0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99


1. FizzBuzz問題

In [38]:
for i in range(1,100):
    if i % 15 == 0:
        print('FizzBuzz')
    else:
        if i % 3 == 0:
            print('Fizz')
        elif i % 5 == 0:
            print('Buzz')
        else:
            print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz


# リスト

In [40]:
[1,2,6,4,8] # 大カッコでリストを宣言する

[1, 2, 6, 4, 8]

In [41]:
x=[1,2,3,4] # 変数に代入できる
print(x)

[1, 2, 3, 4]


In [42]:
print(x[0]) # 0番目の要素を取り出す

1


In [44]:
print(x[0:3]) # 0番目から2番目までの要素を取り出す

[1, 2, 3]


# ベクトル・行列
リストでベクトルを表現できそうだけど、違うデータ構造を使います

（線形代数の計算が色々実装されているから）

In [56]:
import numpy as np # ベクトルや行列を使うためのライブラリ
print(np.array([0,1,2])) # ベクトル

[0 1 2]


In [57]:
print(np.zeros((3,3))) # 3x3のゼロ行列
print(np.ones((3,3))) # 3x3の全要素が1の行列
print(np.identity(3)) # 3x3の単位行列

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [58]:
np.identity(3) @ np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])